Add FastlyModule and FastlyPurgeModule
bearsunday/BEAR.FastlyModule pull request #1
Opened 2022-12-21 07:16 UTC by jingu

2022-12-22 02:39 UTC, jingu commented
@koriym よろしければレビューお願いします！

2022-12-22 07:04 UTC, koriym requested changes

2022-12-22 07:04 UTC, koriym commented on src/ServiceId.php
> + */
```suggestion
/**
 * @Annotation
 * @Target("METHOD")
 * @Qualifier
 * @NamedArgumentConstructor
 */
```

アノテーションサポート不要です。

2022-12-22 07:04 UTC, koriym commented on src/ServiceId.php
> +    }
```suggestion
```

2022-12-22 07:04 UTC, koriym commented on tests/Fake/FakeFastlyPurgeModule.php
> +        $this->enableSoftPurge = $enableSoftPurge;
```suggestion
    /**
     * @SuppressWarnings("PHPMD.BooleanArgumentFlag")
     */
    public function __construct(
        private string $fastlyApiKey,
        private string $fastlyServiceId,
        private bool $enableSoftPurge = true,
        ?AbstractModule $module = null
    ) {
```

2022-12-22 07:04 UTC, koriym commented on tests/Fake/fake-app/src/Resource/Page/BlogPosting.php
> + */
```suggestion
```

アノテーション不要です。

2022-12-22 07:04 UTC, koriym commented on src/FastlyPurgeModule.php
> +final class FastlyPurgeModule extends AbstractModule
モジュールが何を束縛するかドキュメントがあったら良いと思います。

https://ray-di.github.io/manuals/1.0/ja/bp/document_public_bindings.html

2022-12-23 02:07 UTC, jingu commented on src/ServiceId.php
> + */
了解です！
各所消しました。

2022-12-23 02:07 UTC, jingu commented on src/FastlyPurgeModule.php
> +final class FastlyPurgeModule extends AbstractModule
こちらもありがとうございます。コメント追加しました。

2022-12-23 02:41 UTC, koriym reviewed
追加でpushしました。

- php8のコンストラクタ
- モジュールのphpdoc

2022-12-23 02:43 UTC, koriym commented
FastlyPurgeModuleは３番目にboolの引数取る代わりに、
FastlyEnableSoftPurgeModuleと別にしても？とも思いましたが、強い意見でもないです。どうでしょうか？

2022-12-23 02:55 UTC, jingu commented
@koriym 

> FastlyPurgeModuleは３番目にboolの引数取る代わりに、FastlyEnableSoftPurgeModuleと別に

いいと思います！修正しました。

2022-12-23 06:32 UTC, koriym commented on tests/Fake/FakeFastlyPurgeModule.php
> +     */
```suggestion
```

不要です

2022-12-23 06:35 UTC, merged